// Help / Tutorial / FAQ — the SANDBOX. Hard constraint (BUILD_PROMPT §4d):
// this path must NEVER make a real tool call. Enforced structurally:
//
//   1. This module imports NO database, NO messaging, NO blast/job-order code.
//      It receives a question string and returns text. That's its entire API.
//      (tests/deterministic/help-sandbox.test.js proves both the imports and
//      the behavior.)
//   2. Every simulated walkthrough is wrapped in a DEMO banner.
//   3. With an API key, answers are generated by Claude with a system prompt
//      that has no tools at all. Without one, a built-in FAQ answers.

const FAQ = [
  {
    match: ['wrong file', 'file type', 'upload fail', 'bad file', 'unsupported'],
    answer:
      'Job Orders accept .docx and .txt (legacy .doc is best-effort — re-save as .docx if it fails). ' +
      'Contact lists accept .csv and Excel (.xlsx/.xls). If you upload something else, nothing is saved — ' +
      "you'll just be asked to try a different file. Nothing gets imported until you confirm.",
  },
  {
    match: ['cooldown', 'blast guard', 'skip', '3 day', '72'],
    answer:
      'Blast Guard stops anyone from getting a new magic link within the cooldown window (default 72 hours), ' +
      'no matter which category the blast is for. Skipped people are shown in your preview BEFORE you send — ' +
      'e.g. "287 will send, 13 skipped (cooldown)". The window is adjustable in Admin → Settings.',
  },
  {
    match: ['magic link', 'link show', 'category', 'what do candidates see'],
    answer:
      'Each candidate has ONE permanent magic link. It shows every PUBLISHED job order in the category of ' +
      'their most recent blast. They tap "I\'m Interested" on any job right on that page — no texting back needed.',
  },
  {
    match: ['interested', 'interest', 'review', 'report', 'replies'],
    answer:
      'Candidates mark themselves interested on their magic link page. Review Magic Blasts shows each blast ' +
      'with how many were sent, skipped, and how many interested replies came back from it.',
  },
  {
    match: ['stop', 'opt out', 'do not contact', 'dnc', 'unsubscribe'],
    answer:
      'When someone replies STOP (or you mark them Do Not Contact on their record), JobLink treats them as ' +
      'permanently in cooldown — they are always skipped from every blast, in every category.',
  },
  {
    match: ['overwrite', 'duplicate', 'same number', 'different name', 'import'],
    answer:
      'On import, a phone number we already have with a different name gets its NAME updated — nothing else. ' +
      'Last Blast, blast count, and their magic link never change on import. Phone number is the anchor.',
  },
  {
    match: ['last contacted'],
    answer:
      'Last Contacted is never stored. If your upload includes it, it\'s used once — to pick a subset like ' +
      '"the 300 most recent" — and then thrown away. Only Last Blast (when WE last texted them) is kept.',
  },
  {
    match: ['template', 'message', 'placeholder'],
    answer:
      'Blast messages come from templates (Admin → Templates) using {first_name} and {link} placeholders. ' +
      'A template without {link} is rejected — a magic blast without the magic link is just a text.',
  },
];

const DEMO_BANNER = '🧪 DEMO — simulated walkthrough. Nothing here is saved, sent, or published.';

function demoWalkthrough(topic) {
  const walkthroughs = {
    'job order': [
      DEMO_BANNER,
      '1. You pick **New Job Order** and upload "forklift_operator.docx".',
      '2. Tom parses it: Title: Forklift Operator · Category: Industrial · Pay: $18/hr · Shift: 1st (6am–2:30pm) · Location: Waxahachie, TX.',
      '3. You type "pay should be $18.50" — Tom updates the Pay field.',
      '4. You say "publish" — in real life it would go live on the job board. (Demo: nothing was saved.)',
      DEMO_BANNER,
    ],
    blast: [
      DEMO_BANNER,
      '1. You pick **Send Magic Blast** and upload "industrial_list.xlsx" (300 contacts).',
      '2. Tom parses the list: 300 valid numbers, 2 rows with bad phone numbers set aside.',
      '3. You confirm the category: **Industrial** (this can never be skipped).',
      '4. Preview: "287 will send, 13 skipped (cooldown)". You press the **Send** button.',
      '5. Result: 287 sent. (Demo: no texts were actually sent.)',
      DEMO_BANNER,
    ],
    review: [
      DEMO_BANNER,
      '1. You pick **Review Magic Blasts**.',
      '2. You see: Jul 20 · Industrial · 287 sent · 13 skipped · 34 interested so far.',
      DEMO_BANNER,
    ],
  };
  const t = topic.toLowerCase();
  if (t.includes('blast') && !t.includes('review')) return walkthroughs.blast.join('\n');
  if (t.includes('review')) return walkthroughs.review.join('\n');
  if (t.includes('job') || t.includes('order')) return walkthroughs['job order'].join('\n');
  return null;
}

function faqAnswer(question) {
  const q = String(question || '').toLowerCase();
  for (const item of FAQ) {
    if (item.match.some((m) => q.includes(m))) return item.answer;
  }
  return null;
}

/**
 * Answer a help question. Returns a string. This function has no access to
 * the database, the messaging provider, or any write path — by construction.
 */
async function answerHelpQuestion(question) {
  const q = String(question || '').trim();
  if (!q) return 'Ask me anything about JobLink — job orders, magic blasts, cooldowns, imports, or how a flow works.';

  const wantsWalkthrough = /how do i|show me|walk|example|demo|simulate/i.test(q);
  const canned = faqAnswer(q);
  const demo = wantsWalkthrough ? demoWalkthrough(q) : null;

  if (process.env.ANTHROPIC_API_KEY) {
    try {
      const Anthropic = require('@anthropic-ai/sdk');
      const client = new Anthropic();
      const msg = await client.messages.create({
        model: process.env.JOBLINK_HELP_MODEL || 'claude-haiku-4-5',
        max_tokens: 700,
        system:
          'You are the Help assistant inside JobLink, a staffing tool. Answer questions about how JobLink works. ' +
          'JobLink facts: four chat paths (New Job Order, Send Magic Blast, Review Magic Blasts, Help); ' +
          'Blast Guard = 72h default cooldown, global across categories, STOP = permanent; ' +
          'magic link shows Published jobs in the category of the most recent blast; ' +
          'candidates mark interest on the link page; imports overwrite name only; Last Contacted is never stored; ' +
          'job order fields: title, category (Industrial/Administrative/Skilled Trade), pay, shift/hours, location, requirements, description, status. ' +
          'You have NO tools and can take NO actions. If the user asks you to actually create, send, publish, or delete anything, ' +
          'explain that Help is a sandbox and point them to the right button. ' +
          `If a walkthrough helps, simulate one — but it MUST start and end with this exact banner line: "${DEMO_BANNER}"`,
        messages: [{ role: 'user', content: q.slice(0, 2000) }],
      });
      const text = msg.content?.[0]?.text || '';
      if (text) return text;
    } catch { /* fall through to built-in answers */ }
  }

  const parts = [];
  if (canned) parts.push(canned);
  if (demo) parts.push(demo);
  if (!parts.length) {
    parts.push(
      "I can explain any part of JobLink: creating job orders, sending magic blasts, Blast Guard cooldowns, " +
      "what candidates see, imports and the overwrite rule, or reviewing blast results. " +
      'Try asking "how do I send a blast?" for a simulated walkthrough. ' +
      'Note: Help is a sandbox — to actually do these things, use the other three buttons.',
    );
  }
  return parts.join('\n\n');
}

module.exports = { answerHelpQuestion, DEMO_BANNER, faqAnswer, demoWalkthrough };
